name: Publish Docker image to ghcr.io

permissions:
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kobzol
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/kobzol/cargo-pgo:${{ github.ref_name }},ghcr.io/kobzol/cargo-pgo:latest
